import path from "node:path";
import fs from "fs-extra";
import YAML from "yaml";
import type { InterviewAnswers } from "../interview/types.js";

export interface LaunchblocksConfig {
  app_name: string;
  slug: string;
  roles: {
    name: string;
    display_name: string;
    is_owner: boolean;
    is_default: boolean;
    permissions: string[];
  }[];
  owner_role: string;
  default_role: string;
  require_approval: boolean;
  admin_roles: string[];
  llm_access_roles: string[];
  llm_providers: string[];
  ai_tool: string;
  include_billing: boolean;
  billing_model?: "subscription" | "usage" | "both";
}

export function buildConfig(answers: InterviewAnswers): LaunchblocksConfig {
  const slug = answers.appName
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

  return {
    app_name: answers.appName,
    slug,
    roles: answers.roles.map((r) => ({
      name: r.name,
      display_name: r.display_name,
      is_owner: r.is_owner_role,
      is_default: r.is_default_role,
      permissions: [...r.permissions],
    })),
    owner_role: answers.ownerRole,
    default_role: answers.defaultRole,
    require_approval: answers.requireApproval,
    admin_roles: answers.adminRoles,
    llm_access_roles: answers.llmAccessRoles,
    llm_providers: answers.llmProviders,
    ai_tool: answers.aiTool,
    include_billing: answers.includeBilling,
    ...(answers.includeBilling && answers.billingModel
      ? { billing_model: answers.billingModel }
      : {}),
  };
}

export async function writeConfig(
  outputDir: string,
  config: LaunchblocksConfig
): Promise<string> {
  const filePath = path.join(outputDir, "launchblocks.config.yaml");
  const yamlContent =
    "# Launchblocks Project Configuration\n" +
    "# Generated by launchblocks init — do not edit manually\n\n" +
    YAML.stringify(config, { lineWidth: 120 });

  await fs.outputFile(filePath, yamlContent, "utf-8");
  return filePath;
}
